# -------------------------------
# ✨  Global site information
# -------------------------------
title: "Jose Antonio Lorencio Abril" # Site title
description: "Quantitative finance, machine learning, and big data projects."
url: "https://lorenc1o.github.io"        # full URL without trailing /
baseurl: ""                              # keep empty for a user/organisation site

# Social handles
github_username: Lorenc1o
linkedin_username: lorencio-abril

author:
  name: Jose Antonio Lorencio Abril
  email: joseantoniolorencio@gmail.com

# -------------------------------
# Build settings
# -------------------------------
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag           # ➟ automatic meta‑tags / OpenGraph / JSON‑LD
  - jekyll-multiple-languages-plugin

# -------------------------------
# i18n
# -------------------------------
languages: ['en', 'es', 'fr']
default_lang: 'en'
exclude_from_localization:
  - "assets"
  - "index.html"

# -------------------------------
# Incremental build exclusions
# -------------------------------
# Uncomment anything else you need
# exclude:
#   - node_modules/
#   - vendor/